### ISSUE TITLE
Support more modern buzz words

### ISSUE THREAD

**Issue by Zehvogel** [fceschmidt/bullshit-arch#3]
to name a few:
hyper-converged
kubernetes
off-the-shelf
bare-metal
infrastructure
planet scale
hybrid
best-of-breed
DevOps
data science

**Comment by fceschmidt** [comment]
Resolved with 033f541

**Comment by Zehvogel** [comment]
ultra-fast
ultra-compact
crash-proof
key-value
enterprise-grade
internet-scale
microservice
self-contained
in-memory
maintenance-free
mission critical
